"""
Django settings for DigitalTwin project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sys

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# GDAL and PROJ_LIB settings for PostGIS
# GDAL/GEOS Configuration for Windows
if os.name == 'nt':
    # Get the virtual environment path
    venv_path = Path(sys.executable).parent.parent
    osgeo_path = venv_path / 'Lib' / 'site-packages' / 'osgeo'
    
    if osgeo_path.exists():
        # Add osgeo to PATH so DLLs can be found
        osgeo_bin = str(osgeo_path)
        if osgeo_bin not in os.environ.get('PATH', ''):
            os.environ['PATH'] = osgeo_bin + os.pathsep + os.environ.get('PATH', '')
        
        # Set GDAL library path
        gdal_dll = osgeo_path / 'gdal.dll'
        if gdal_dll.exists():
            GDAL_LIBRARY_PATH = str(gdal_dll)
        
        # Set GEOS library path
        geos_dll = osgeo_path / 'geos_c.dll'
        if geos_dll.exists():
            GEOS_LIBRARY_PATH = str(geos_dll)
        
        # Set GDAL data paths
        gdal_data = osgeo_path / 'data' / 'gdal'
        if gdal_data.exists():
            os.environ['GDAL_DATA'] = str(gdal_data)
        
        proj_lib = osgeo_path / 'data' / 'proj'
        if proj_lib.exists():
            os.environ['PROJ_LIB'] = str(proj_lib)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
MAPBOX_ACCESS_TOKEN = os.environ.get("MAPBOX_ACCESS_TOKEN")
TITILER_BASE_URL = os.environ.get("TITILER_BASE_URL")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_extensions",
    # "rest_framework",
    "crispy_forms",
    "crispy_tailwind",    
    'core.apps.CoreConfig',    
    "importer",  
    "common",
    "watersupply",    
    "mainMap",
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "DigitalTwin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["Templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'common.version.version_context',
]

WSGI_APPLICATION = "DigitalTwin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.environ.get("DATABASE_NAME"),
        "USER": os.environ.get("DATABASE_USER"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD"),
        "HOST": os.environ.get("DATABASE_HOST"),
        "PORT": os.environ.get("DATABASE_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

COORDINATE_SYSTEM = int(os.environ.get("COORDINATE_SYSTEM", 28992))  # Amersfoort / RD New


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "common/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"

CRISPY_TEMPLATE_PACK = "tailwind"
